CONFIG_ZMK_KEYBOARD_NAME="mykeyboard2"
CONFIG_USB_DEVICE_PRODUCT="mykeyboard_usb"
CONFIG_BT_DEVICE_NAME="mykeyboard_bt"
CONFIG_USB_DEVICE_VID=0x1D50
CONFIG_USB_DEVICE_PID=0x615E
CONFIG_USB_DEVICE_MANUFACTURER="ZMK Project"

#
# HID
#
CONFIG_ZMK_HID_REPORT_TYPE_HKRO=y
# CONFIG_ZMK_HID_REPORT_TYPE_NKRO is not set
CONFIG_ZMK_HID_KEYBOARD_REPORT_SIZE=6
CONFIG_ZMK_HID_CONSUMER_REPORT_SIZE=6
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
# CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC is not set

#
# Output Types
#
CONFIG_ZMK_USB=y
CONFIG_USB_NUMOF_EP_WRITE_RETRIES=10
CONFIG_ZMK_BLE=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=512
CONFIG_ZMK_BLE_THREAD_PRIORITY=5
CONFIG_ZMK_BLE_KEYBOARD_REPORT_QUEUE_SIZE=256
CONFIG_ZMK_BLE_CONSUMER_REPORT_QUEUE_SIZE=5
# CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START is not set
# CONFIG_BT_GATT_NOTIFY_MULTIPLE is not set
CONFIG_BT_DEVICE_APPEARANCE=961
# CONFIG_ZMK_BLE_PASSKEY_ENTRY is not set
# end of Output Types
# end of HID


CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y

## ZMK Studio ##
# references: https://zmk.dev/docs/config/studio
CONFIG_ZMK_STUDIO=n

## Rotary Encoder ##
# references: https://zmk.dev/docs/config/encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

## Battery Reporting ##
# references: https://zmk.dev/docs/config/battery
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

## Xiao LED ##
# references: https://github.com/caksoylar/zmk-rgbled-widget?tab=readme-ov-file#configuration-details
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=500
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=60
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
##常に
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
##変わった時
# CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=y　
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=1
